version: "3"

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    #Rede a qual perrence o containner
    networks:
      - app-network
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
  db:
    image: mysql:5.7
    #Comando que evita erros (Se não usar é muito choro e ranger de dentes para programador)
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

#Construção da rede
networks:
  #Nome e configuração da rede
  app-network:
    driver: bridge
