apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template: #aqui eu uso o modelo de um POD para meu deployment criar
    metadata:
      labels:
        app: nginx
    spec: #spec do meu POD
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        # Cria arquivo index. e chama entrypoint nginx
        command: ["/bin/sh","-c","touch /usr/share/nginx/html/index.php; nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        # Monta os volumes no containner
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true

      # Na linha do container cria o volume
      #configura os volume
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key : nginx.conf
              # Qdo montado qual será o nome do arquivo
              path: nginx.conf
