apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec: # spec do deployment
  replicas: 1

  selector: # Selector utilizado na criação do service
    matchLabels:
      app: mysql-server
      tier: db

  template: # template do Pod
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: # spec do Pod
      containers:
      - image: mysql:5.7
        name: mysql-server
        env: # Variáveis de ambiente
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306



