apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec: #configuracoes do deployment e nao do POD
  selector:
    matchLabels:
      app: hello-nginx
  replicas:3
  template: #aqui eu uso o modelo de um POD para meu deployment criar
    metadata:
      labels:
        app: hello-nginx
    spec: #spec do meu POD
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
        - containerPort: 80
