apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  # Faz a busca pelo serviço usando key = app e valor hello-nginx
  selector:
    app: hello-nginx
